language: ruby
sudo: false
cache: bundler

rvm:
  - "2.3"
  - "2.4"
  - "2.5"

env:
  - "RAILS_VERSION=rails5"
  - "RAILS_VERSION=rails4"
  - "RAILS_VERSION=pojs"

script: "if [ $PERFORMANCE_SPECS ];then bundle exec rake performance_specs --trace; else bundle exec rake --trace; fi"

matrix:
  fast_finish: true
  include:
    - env:
        - "PERFORMANCE_SPECS=true"
        - "RAILS_VERSION=rails5"

before_install:
  - gem update --system
  - gem install bundler
