language: ruby
sudo: false
cache: bundler

addons:
  chrome: stable

rvm:
  - "2.3"
  - "2.4"
  - "2.5"

env:
  - "RAILS_VERSION=rails5"
  - "RAILS_VERSION=rails4"
  - "RAILS_VERSION=pojs"

script: "if [ $PERFORMANCE_SPECS ];then bundle exec rake performance_specs --trace; else bundle exec rake --trace; fi"

matrix:
  fast_finish: true
  include:
    - env:
        - "PERFORMANCE_SPECS=true"
        - "RAILS_VERSION=rails5"

before_install:
  - gem update --system
  - if [ "$RAILS_VERSION" == rails4 ];
    then
      find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete;
      find /home/travis/.rvm/rubies -wholename '*bundler*.gemspec' -delete;
      gem install bundler --version '<  2.0.0';
    else
      gem install bundler;
    fi
